name: Deployment
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DB_URL: postgresql+pg8000://${{ secrets.PGUSER }}:${{ secrets.PGPASSWORD }}@${{ secrets.PGHOST }}:${{ secrets.PGPORT }}/${{ secrets.PGDATABASE }}
      TEST_DB_URL: sqlite:///./test.db
    steps:
      - name: server ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: ec2-18-219-39-223.us-east-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd bhub-api-project/
            echo "SQLALCHEMY_DATABASE_URL=$DB_URL" >> .env
            echo "SQLALCHEMY_TESTING_DATABASE_URL=$TEST_DB_URL" >> .env
            git pull origin main
            sudo docker-compose up -d --force-recreate
            
