name: Deployment
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: server ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: ec2-18-219-39-223.us-east-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd bhub-api-project/
            git pull origin main
            git status
            
