name: Deployment
on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: server ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: ec2-18-219-39-223.us-east-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd bhub-api-project/
            rm -rf .env
            git pull origin main
            echo "SQLALCHEMY_DATABASE_URL=postgresql+pg8000://${{ secrets.PGUSER }}:${{ secrets.PGPASSWORD }}@${{ secrets.PGHOST }}:${{ secrets.PGPORT }}/${{ secrets.PGDATABASE }}" > .env
            echo "SQLALCHEMY_TESTING_DATABASE_URL=sqlite:///./test.db" >> .env
            sudo docker-compose up -d --force-recreate
            
